# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patty O'Hara
email: patty.ohara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  All things front-end (and maybe even some back-end) Web Dev.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pattyok.github.io" # the base hostname & protocol for your site
twitter_username: pattyok
github_username:  pattyok

# Build settings
markdown: kramdown
